services:
  - type: web
    name: django-backend
    env: python
    pythonVersion: 3.11.9
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    plan: starter
    region: singapore
